services:
  - type: web
    name: n8n-1
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    port: 5678
    startCommand: n8n start
envVars:
  - key: N8N_EDITOR_BASE_URL
    value: https://n8n-1-63gt.onrender.com
  - key: WEBHOOK_TUNNEL_URL
    value: https://n8n-1-63gt.onrender.com
