services:
  - type: web
    name: n8n-1
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-1.onrender.com
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-1.onrender.com
