services:
  - type: web
    name: n8n-1
    env: docker
    disk:
      name: n8n-disk
      mountPath: /data
      sizeGB: 1
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-1-63gt.onrender.com
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-1-63gt.onrender.com
